// program floopy
// Generated by program genpgm
//

#include "lists.h"

int main(int argc, char* argv[])
{
lists_register();
ifstream if0;
ofstream of0;
ofstream of1;

strlnk* parm[10]; // up to 10 parms from command line
for (int i=0;i<argc-1;i++)parm[i] = new strlnk(argv[i+1]);

if (argc!=4) {
  cout<<"*******************************************************************\n";
  cout<<"*******************************************************************\n";
  cout<<"Operation: floopy <in_files> <out_files>\n\n";
  cout<<"USAGE:\n";
  cout<<"   <in_file0>:\n";
  cout<<"   <out_file0>:\n";
  cout<<"   <out_file1>:\n";
  cout<<"*******************************************************************\n";
  cout<<"*******************************************************************\n";

return 1;
}
if0.open(parm[0]->str1,ios::in);
if (!if0) { 
cerr<<"Error: cannot open input file "<<*parm[0]<<"\n";
}
of0.open(parm[1]->str1,ios::out);
if (!of0) { 
cerr<<"Error: cannot open output file "<<*parm[0]<<"\n";
}
of1.open(parm[2]->str1,ios::out);
if (!of1) { 
cerr<<"Error: cannot open output file "<<*parm[1]<<"\n";
}
if0.close();
of0.close();
of1.close();
return 0;
}

